# Generated by Django 4.1.1 on 2022-09-13 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(max_length=255, null=True)),
                ('price', models.CharField(max_length=255, null=True)),
                ('quantity', models.BigIntegerField(max_length=100, null=True)),
                ('buyer_mobile', models.CharField(max_length=255)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('product_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_website.product')),
            ],
            options={
                'db_table': 'cart',
                'managed': True,
            },
        ),
    ]
