# Generated by Django 4.0.6 on 2022-09-09 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0002_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
