# Generated by Django 4.1.1 on 2022-09-13 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_website', '0003_users_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'managed': True},
        ),
    ]
